"""Reuse the existing discriminator procedure and compare quantiles with nominal OT."""
from pathlib import Path
import argparse
import json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score
import evaluate_ot_closure as closure

HERE = Path(__file__).resolve().parent


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--calibrated", type=Path, default=HERE / "results/quantile_1d_energy")
    parser.add_argument("--out", type=Path, default=HERE / "results/quantile_1d_closure")
    parser.add_argument("--nominal-closure", type=Path, default=HERE / "results/task6_nominal_mod4_closure")
    args = parser.parse_args()
    completed = json.loads((args.calibrated / "completion.json").read_text())
    if completed.get("completed") is not True or completed.get("tb_validation_used_for_fitting") is not False:
        raise ValueError("Incomplete/unverified quantile calibration.")
    for cls in ["e", "p", "C"]:
        for representation in ["z_enc", "logits"]:
            path = args.nominal_closure / f"{cls}_{representation}_calibrated_evaluation.npz"
            if not path.is_file():
                raise FileNotFoundError(path)
    closure.CALIBRATED = args.calibrated
    closure.OUT = args.out
    # Existing Task-2 row splits and discriminator hyperparameter selection.
    closure.main()
    summaries = []
    for representation in ["z_enc", "logits"]:
        fig, axes = plt.subplots(1, 3, figsize=(15, 4.8), layout="constrained")
        for ax, cls in zip(axes, ["e", "p", "C"]):
            reference = None
            for status, folder, filename_status, color, label in [
                ("raw", args.out, "raw", "#2166ac", "MC originale"),
                ("nominal_OT", args.nominal_closure, "calibrated", "#2ca02c", "OT nominale mod4"),
                ("quantiles_1d", args.out, "calibrated", "#d95f02", "Quantili 1-D per energia")]:
                with np.load(folder / f"{cls}_{representation}_{filename_status}_evaluation.npz", allow_pickle=False) as saved:
                    rows = {key: saved[key] for key in ["mc_test_rows", "tb_test_rows", "domain_label"]}
                    if reference is None:
                        reference = rows
                    else:
                        for key in reference:
                            np.testing.assert_array_equal(reference[key], rows[key])
                    auc = float(roc_auc_score(saved["domain_label"], saved["score_tb"]))
                    ax.plot(saved["fpr"], saved["tpr"], color=color, label=f"{label}: AUC={auc:.4f}")
                    summaries.append(dict(cls=cls, representation=representation, method=status, heldout_auc=auc))
            ax.plot([0,1], [0,1], "--", color="gray")
            ax.set(title=cls, xlabel="False positive rate", ylabel="True positive rate", xlim=(0,1), ylim=(0,1))
            ax.grid(alpha=.2)
            ax.legend(loc="lower right", fontsize=8)
        fig.suptitle(f"MC vs TB validation — {representation}\nStessi eventi di test; miscele energetiche bilanciate")
        for extension in ["png", "pdf"]:
            # Replace the generic before/after-OT figure generated by the reused procedure.
            fig.savefig(args.out / f"roc_{representation}.{extension}", dpi=220)
        plt.close(fig)
    table = pd.DataFrame(summaries)
    table.to_csv(args.out / "auc_three_way_comparison.csv", index=False)
    config_path = args.out / "config.json"
    config = json.loads(config_path.read_text())
    config["calibration_method"] = "1D quantile maps, per class and energy"
    config["note"] = ("Discriminator test rows held out from discriminator training. MC events available for quantile fitting; "
                      "TB validation excluded from quantile fitting. Energy-matched discriminator evaluation.")
    config_path.write_text(json.dumps(config, indent=2), encoding="utf-8")
    print(table.pivot(index=["cls", "representation"], columns="method", values="heldout_auc").to_string())
    print("PASS: closure comparison on identical test rows. Saved:", args.out.resolve())


if __name__ == "__main__":
    main()
